---
- name: Download neovim release tarball
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/neovim/neovim/releases/download/v{{ setup_neovim_version }}/nvim-linux-{{ ansible_architecture }}.tar.gz"
    dest: /opt
    remote_src: true
    creates: /opt/nvim-linux-{{ ansible_architecture }}

- name: Symlink nvim binary
  become: true
  ansible.builtin.file:
    src: "/opt/nvim-linux-{{ ansible_architecture }}/bin/nvim"
    dest: /usr/local/bin/nvim
    state: link
    force: true

- name: Create config directory for neovim
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: directory
    mode: "0755"

- name: Copy configuration files for neovim
  ansible.builtin.copy:
    src: "files/config/"
    dest: "{{ ansible_env.HOME }}/.config/nvim/"
    mode: "0644"
    backup: true
  changed_when: false # Bootstrapping touches lockfile

- name: Sync lazy plugins for neovim
  ansible.builtin.command: nvim --headless +Lazy! restore +qa
  changed_when: false
