# Set prefix key to Ctrl-s instead of default Ctrl-b
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

# Use vi keybindings
set-option -g mode-keys vi

# Start windows and panes at 1
set-option -g base-index 1
set-window-option -g pane-base-index 1

# Keep window numbers contiguous
set-option -g renumber-windows on

# Disable the status bar
set-option -g status off

# Fix escape delay
set-option -sg escape-time 10

