# Set prefix key
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

# Use vi keybindings
set-option -g mode-keys vi
bind -n 'C-M-h' resize-pane -L 5
bind -n 'C-M-j' resize-pane -D 5
bind -n 'C-M-k' resize-pane -U 5
bind -n 'C-M-l' resize-pane -R 5

# Start windows and panes at 1
set-option -g base-index 1
set-window-option -g pane-base-index 1

# Keep window numbers contiguous
set-option -g renumber-windows on

# Fix escape delay
set-option -sg escape-time 10

# Enable mouse for initial pane focus
set -g mouse on

# Create horizontal split with ctrl-t
bind-key -n 'C-t' split-window -v -l 30%

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

run -b '~/.tmux/plugins/tpm/tpm'

