---

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - idempotence
    - verify
    - destroy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: ubuntu:24.04
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: debug
      callbacks_enabled:
        - timer
        - profile_tasks
        - profile_roles
    env:
      ANSIBLE_FORCE_COLOR: "true"
verifier:
  name: testinfra
  directory: ../../roles
  options:
    verbose: true
