---
- name: Ensure fonts directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts"
    state: directory
    mode: "755"

- name: Download nerd font
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ install_fonts_nerd_font }}.tar.xz
    dest: /tmp/{{ install_fonts_nerd_font }}.tar.xz
    mode: "644"

- name: Unpack nerd font
  ansible.builtin.unarchive:
    src: /tmp/{{ install_fonts_nerd_font }}.tar.xz
    dest: "{{ ansible_env.HOME }}/.local/share/fonts"
    remote_src: true
  notify: Update font cache
