---
- name: Install i3 and related packages
  become: true
  ansible.builtin.apt:
    name: "{{ install_i3_packages }}"
    state: present
    update_cache: true

- name: Create i3 config dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "755"
  loop:
    - "{{ ansible_env.HOME }}/.config/i3"
    - "{{ ansible_env.HOME }}/.config/i3blocks"

- name: Copy i3 config files
  ansible.builtin.copy:
    src: "i3_config"
    dest: "{{ ansible_env.HOME }}/.config/i3/config"
    mode: "644"
    backup: true
  notify: Restart i3

- name: Copy i3 blocks configuration
  ansible.builtin.copy:
    src: "i3blocks_config"
    dest: "{{ ansible_env.HOME }}/.config/i3blocks/config"
    mode: "644"
    backup: true
  notify: Restart i3

- name: Create machine-specific display config template
  ansible.builtin.copy:
    content: |
      # Place machine specific workspace/display configuration here
      # example:
      # workspace 1 output HDMI-1
    dest: "{{ ansible_env.HOME }}/.config/i3/outputs.conf"
    mode: "644"
    force: false

- name: Copy scripts
  become: true
  ansible.builtin.copy:
    src: "scripts/"
    dest: "/usr/local/bin/"
    mode: "755"

- name: Configure rofi
  ansible.builtin.import_tasks: rofi.yaml
